### PR TITLE
feat: custom v-observe-visibility directive

### LINKED ISSUE #64: Improve use of v-observe-visibility
We use this directive in some places to record when we have viewed an item.  This would be more reliable if we had two occurrences - one at the top of an item, one at the bottom, and we only recorded the view once both of them had become visible (in either order).

We should do this with a generic component, e.g. OurVisible which:
* has a default slot
* tracks visibility of the top and bottom
* emits an event

So then we can place anything within it that we want to track visibility for.  For now let's use it in:

- [ ] MessageSummary
- [ ] OurMessage

### PR DESCRIPTION
**Pull request by untael**
closes #64 

In scope of this PR `vue3-observe-visibility` library was replaced by new custom directive based on [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).

I also added ability to add multiple thresholds to track different positions of the element. Usage is still the same.

Now we have access to additional argument of the callback to get access to:

* isTopVisible - boolean true when top of the element is visible
* isBottomVisible - boolean true when bottom of the element is visible
* [entry](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserverEntry)
* [observer](https://developer.mozilla.org/en-US/docs/Web/API/IntersectionObserver)

**Notes:**
* `intersection` name of property from the payload was changed to `options`

* to make `isTopVisible`/`isBottomVisible` works you need to specify threshold as an array like `[0, 1]` and in this case observer will fire two events - firs time when the very first pixel of element will appear on the screen, second time for the very last pixel. More info about [threshold](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API).

PS: there is no need to specify wrapper component with slots for that purposes, you can just observe element what you want to.

### CODE REVIEW

**Comment by untael** [comment]
> What happens if the element is too large to fit in the viewport? I could be wrong, but I think we would then never fire the event.

For such edge cases we can extract `observer` field which contains `isIntersecting` property (true/false)

**Comment by edwh** [comment]
OK. Can you do that?

The logic for spotting when the element has been viewed is shared, so it either needs to be in the directive itself or in a composable.

**Comment by untael** [comment]
> OK. Can you do that? The logic for spotting when the element has been viewed is shared, so it either needs to be in the directive itself or in a composable.
> […](#)
> On 14 February 2024 19:13:12 GMT, Pavel Mironov ***@***.***> wrote: > What happens if the element is too large to fit in the viewport? I could be wrong, but I think we would then never fire the event. For such edge cases we can extract `observer` field which contains `isIntersecting` property (true/false) -- Reply to this email directly or view it on GitHub: [#71 (comment)](https://github.com/Freegle/iznik-nuxt3/pull/71#issuecomment-1944437244) You are receiving this because you commented. Message ID: ***@***.***>

Before implementing that can you explain exact case for what we need that functionality in details?

I'm wondering why specifying thresholds like 0.1-0.25 is not enough to check when element was intersected.

**Comment by edwh** [comment]
If there is only a fraction of an element on screen then people are often not actually looking at that element. They're looking at something else which is on the screen. So it has been visible, but they haven't seen it. Therefore I want to be able to mark items like that as seen only when all of it has been visible, not just a fraction of it.

Some elements may be larger than the viewport. 
Take the example of a ChitChat item with a photo. On small mobile screens it will be taller than the screen. So we need to be able to handle that case.

**Comment by untael** [comment]
Hi @edwh. I added this functionality into directive. To use it you need to pass `observeFullElement: true,` in options (no need to specify thresholds). Now when element will be viewed fully you can extract `entryWasObserved` as well as `entryObservedCount` (I added count because probably you'll need it for something)

**Comment by edwh** [comment]
Thanks.  It doesn't look like you're using `observeFullElement` in `MessageSummary` and `OurMessage`, though.  That's the point of this PR.  

I'm also not sure the logic is right.

- Consider the case we've discussed where the element is taller than the viewport.  Your observer will be called with the top visible but the bottom not visible, then we'll set `entryTopWasObserved` true and `entryBottomWasObserved` false.  Then as we scroll down it will be called with the bottom visible but the top not visible, we'll set we'll set `entryTopWasObserved` false and `entryBottomWasObserved` true.  We'll never set `entryWasObserved` true.
- If we pass `observeFullElement` then we shouldn't callback for the intermediate states.  We should only call back when `entryWasObserved` becomes true because that's what we're interested in.

I want to make sure that the calling code, e.g. in `MessageSummary` doesn't have to do any logic or checking - it just gets a callback when the whole element has been observed.

**Comment by untael** [comment]
I updated PR according to described requirements. According usage, can you explain in details how exactly you want to use this flag (entryWasObserved)? Do we need to just emit once we callback we'll get `true`?
Another question is why do we need to track visiblity `MessageSummary` component in case it is nested in `OurMessage`?

**Comment by edwh** [comment]
> Do we need to just emit once we callback we'll get `true`?

Yes.

> why do we need to track visiblity `MessageSummary` component in case it is nested in `OurMessage`?

I'm not quite sure I understand your question.  But it looks like in `OurMessage` the emit of `visible` is never used in a parent, and therefore we can remove `v-observe-visibility` from there.

**Comment by untael** [comment]
> > Do we need to just emit once we callback we'll get `true`?
> 
> Yes.
> 
> > why do we need to track visiblity `MessageSummary` component in case it is nested in `OurMessage`?
> 
> I'm not quite sure I understand your question. But it looks like in `OurMessage` the emit of `visible` is never used in a parent, and therefore we can remove `v-observe-visibility` from there.

Thats exactly what I meant! If we're not using emit from `OurMessage` we can omit directive on this component and use it in `MessageSummary`. I just thought you have some plans for `OurMessage` as well.

**Comment by edwh** [comment]
No, I think it's just leftover code from an earlier version.

**Comment by untael** [comment]
I also removed unused emit from `MessageSummary`.

**Pull request merged**
