### PR TITLE
Fix #33

### LINKED ISSUE #33: "Freegle It" button briefly reappears
When you post an OFFER/WANTED, the "Freegle It" button disappears and is replaced by a progress bar.  Once the post is complete you're then sent to another page.  But the "Freegle It" button briefly reappears before the page route completes, which looks a bit messy.  We shouldn't show the button once the post has succeeded.

### PR DESCRIPTION
**Pull request by smellyshovel**
This PR closes #33.

### CODE REVIEW

**Comment by smellyshovel** [comment]
Fix description:

Don't reset the "submitting" flag. It's correctly reset at a correct point in time, but there are router navigations ongoing. Even if you add `await` for `router.push(...)`, the promise would be resolved after the navigation is considered successful (the URL is changed), but *before the new component gets loaded*. That's why the button remains visible.
If we instead don't reset the flag at all, then it doesn't matter how long it takes for the new page to load - the button won't ever become visible again.

**Comment by edwh** [comment]
I think we need to reset the flag in the `catch`, because there won't be routes outstanding.

Please also add a comment to explain why we _don't_ reset it, otherwise we'll look at it later and think it's a bug.

**Comment by smellyshovel** [comment]
> I think we need to reset the flag in the `catch`, because there won't be routes outstanding.
> 
> Please also add a comment to explain why we _don't_ reset it, otherwise we'll look at it later and think it's a bug.

You're right with both. Will do :+1:

**Comment by smellyshovel** [comment]
@edwh addressed both.

**Pull request merged**
