### PR TITLE
Add drag & drop for photos

### LINKED ISSUE #11: Change primary photo
This needs some discussion before implementation. The basic point is that when you upload multiple photos, the first is used as the primary image, which might not be what you want.  We need an intuitive way to change the primary photo.

### PR DESCRIPTION
**Pull request by misterpekert**
Add very simple drag&drop for pictures when creating a post. Should close #11 from the frontend part.

### CODE REVIEW

**Review by edwh — CHANGES_REQUESTED** [review]
This works fine for the initial message post, but you also need to change the message edit case.

I've done the corresponding server changes.

**Comment by misterpekert** [comment]
> This works fine for the initial message post, but you also need to change the message edit case.
> 
> I've done the corresponding server changes.

@edwh yeah, my bad. I've completely forgotten about that one. Luckily, it was a quick change. Please take another look. it should be good now.

I've also noticed that the order of the attachments is not preserved after saving, only the "primary" photo changes. Is it something that you expect?

**Comment by edwh** [comment]
> I've also noticed that the order of the attachments is not preserved after saving, only the "primary" photo changes. Is it something that you expect?

Yes, I only store primary vs non-primary, not the whole order.

**Comment by edwh** [comment]
@misterpekert FYI this broke the rotate and delete buttons.  @chriscant has done a slightly odd but effective fix in b337f25a7561cea1eefdc84551602dd30caac476

**Pull request merged**
