### PR TITLE
Include core-js's polyfill for to-sorted

### LINKED ISSUE #14: Add toSorted polyfill
We added a use of `toSorted` in `myposts`.  This broke some older browsers.  We should add a polyfill so that we don't have to remember not to use it.

### PR DESCRIPTION
**Pull request by smellyshovel**
Should close #14 when merged.

### CODE REVIEW

**Comment by smellyshovel** [comment]
Right now by the Netlify's preview link.

Supported browsers:
Screenshot_20231004_130649

Unsupported browsers:
Screenshot_20231004_130731

**Comment by smellyshovel** [comment]
Doesn't seem to work if adding the `import` to the `nuxt.config.ts` file. Will try to add it to the relevant component directly.

**Comment by smellyshovel** [comment]
Older browsers work just fine after I include the `import` directly on the component level.

Screenshot_20231004_132810

So, generally, the issue's resolved. But I don't really like the idea of importing polyfills on the component level. Maybe you know and could tell me what's considered the Nuxt application's main entry point? Something like `main.ts` or `index.ts`. I can't find anything of the sort, and googling tells me it should be `nuxt.config.ts`, but that doesn't work.

So, ideally, would be nice to have a single place where we include/enable all the required polyfills.

**Comment by edwh** [comment]
> Maybe you know and could tell me what's considered the Nuxt application's main entry point?

Try `app.vue`?

**Comment by smellyshovel** [comment]
> > Maybe you know and could tell me what's considered the Nuxt application's main entry point?
> 
> Try `app.vue`?

Indeed, that also seems to work.

**Review by edwh — APPROVED** [review]

**Pull request merged**
